# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name = "skybolt-ruby"
  spec.version = "3.1.0"
  spec.authors = ["Jens Roland"]
  spec.email = ["mail@jensroland.com"]

  spec.summary = "High-performance asset caching for multi-page applications"
  spec.description = "Reads the render-map.json generated by @skybolt/vite-plugin and outputs optimized HTML tags with intelligent caching via Service Workers."
  spec.homepage = "https://github.com/JensRoland/skybolt-ruby"
  spec.license = "MIT"
  spec.required_ruby_version = ">= 3.0.0"

  spec.metadata["homepage_uri"] = spec.homepage
  spec.metadata["source_code_uri"] = "https://github.com/JensRoland/skybolt-ruby"
  spec.metadata["changelog_uri"] = "https://github.com/JensRoland/skybolt-ruby/blob/main/CHANGELOG.md"

  spec.files = Dir["lib/**/*", "README.md", "LICENSE"]
  spec.require_paths = ["lib"]
end
